name: raspi_dart_led_control
description: A minimal command-line app using FFI to demonstrate GPIO control on Raspberry Pi.
version: 1.0.0
repository: https://github.com/cervm/raspi_dart_led_control

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  lints: ^4.0.0
